package com.freelibrary.catalogtool

import com.freelibrary.shared.Manifest
import com.freelibrary.shared.ManifestEntry
import java.nio.file.Path
import java.time.LocalDate

private const val TODAY_RSS_URL = "https://www.gutenberg.org/cache/epub/feeds/today.rss"

/**
 * Entry point for the nightly incremental sync: checks Project Gutenberg's
 * today.rss feed for books posted or updated in the last 24 hours, fetches
 * only those individual books' RDF directly, and updates the checked-out
 * freelibrary-catalog-data export (manifest.json + books/) in place.
 *
 * Deliberately does not touch the bundled catalog.sqlite - that is only
 * regenerated by the full pipeline (see [main] in Main.kt), on a much less
 * frequent, deliberate schedule. This entry point exists specifically to
 * keep existing installs current via the app's own sync client, without
 * ever needing a full ~126MB archive re-download for a handful of new
 * books. Run via `./gradlew :catalog-tool:nightlySync`.
 */
fun main() {
    val exportDir = Path.of("data/export")
    val exportBooksDir = exportDir.resolve("books")
    val today = LocalDate.now().toString()

    val bookIds =
        try {
            parseRssBookIds(fetchBytes(TODAY_RSS_URL))
        } catch (e: Exception) {
            println("Failed to fetch or parse today.rss: ${e.message}")
            return
        }

    println("Found ${bookIds.size} book id(s) in today's feed.")

    val existingManifest = readManifest(exportDir)
    val manifestEntries = existingManifest?.books?.associateBy { it.externalId }?.toMutableMap() ?: mutableMapOf()
    val baselineVersion = existingManifest?.baselineVersion ?: today

    var updatedCount = 0
    var skippedCount = 0
    var failedCount = 0
    val failureSamples = mutableListOf<String>()

    for (externalId in bookIds) {
        try {
            Thread.sleep(200)
            val rdfBytes = fetchBytes("https://www.gutenberg.org/cache/epub/$externalId/pg$externalId.rdf")
            val book = parseRdf(rdfBytes)
            if (book == null) {
                skippedCount++
                continue
            }

            writeBookExport(exportBooksDir, book.toExport(lastModified = today))
            manifestEntries[externalId] = ManifestEntry(externalId = externalId, lastModified = today)
            updatedCount++
        } catch (e: Exception) {
            failedCount++
            if (failureSamples.size < 5) {
                failureSamples.add("$externalId: ${e.message}")
            }
        }
    }

    writeManifest(
        exportDir,
        Manifest(generatedAt = today, baselineVersion = baselineVersion, books = manifestEntries.values.toList()),
    )

    println("Done. Updated: $updatedCount, skipped: $skippedCount, failed: $failedCount")
    if (failureSamples.isNotEmpty()) {
        println("Sample failures:")
        failureSamples.forEach { println("  $it") }
    }
}
